### ISSUE TITLE
Erocci doesn't manage underscore on attributes

### ISSUE THREAD

**Issue by cgourdin** [erocci/erocci_backend_dbus#11]
Hi,
I have an attribute with name : disk_size, Erocci give me an error when i try to save a resource :

```
=ERROR REPORT==== 23-Mar-2016::13:33:41 ===
Error processing request: {parse_error,invalid_key}
```

If i define the attribute with "disksize", it works.

**Comment by jeanparpaillon** [comment]
Should be fixed in https://github.com/erocci/erocci_core/commit/fa6770cf137ba2f5437a83d0c4f439f2c55e8812

Can you check ?

**Comment by cgourdin** [comment]
it worked. 
Thanks.
