### ISSUE TITLE
Owners et backend operations.

### ISSUE THREAD

**Issue by cgourdin** [erocci/erocci_backend_dbus#14]
Hello,

I need to know if a backend manage one owner on one instance of the application, or manage multiple owners on the same instance. It's important to clear that point as it has a direct impact on Erocci-Dbus-java backend code.

**Comment by jeanparpaillon** [comment]
Question is somehow related to #4 but not only.
I suppose it backends SHOULD handle multiple owner.
As currently implemented (with opaque 'owner'), it is impossible.
Owner should be a duet {user, group} for that.

Will modify the D-Bus API.

**Comment by jeanparpaillon** [comment]
D-Bus API now explicitly set owner AND group for entities
