### ISSUE TITLE
Long time operations, backend and Erocci interaction

### ISSUE THREAD

**Issue by cgourdin** [erocci/erocci_backend_dbus#15]
Hello,

Erroci leave me with a timeout systematically on long time operations (>10 secs). 
I think this should be in specification somewhere, for further backend development.
I need to know if all final (on real things) actions and operations are to be asynchronous (multithreading) to avoid Erroci time out on query. If yes, this cause a second question, how to manage the operation supervision between Erocci and backend (states, etc.) ? 
For example, The action has no return values, if operation failed, there's no way to tell Erocci the operation has been failed (in case of multithreading scheme).

**Comment by jeanparpaillon** [comment]
Timeouts could be parameter, of course, but the "REST" way is to return a value indicating the request has been handled, but result is not available (see HTTP code 202).

See my update on README.md (TODO)

**Comment by cgourdin** [comment]
Ok so to manage actions and all operations we need to implement asynchronous (multithreading) operations. 
Thanks !
