### ISSUE TITLE
Erocci has internal error when using the cloud.xml schema

### ISSUE THREAD

**Issue by MaelAudren** [erocci/erocci_backend_dbus#16]
I try to use the cloud connector from erocci-dbus-java but erocci doesn't seems to recognize the cloud.xml schema generated from https://github.com/occiware/ecore/tree/master/clouddesigner/org.occiware.clouddesigner.occi.cloud.  
The response to the curl request is "500 internal server error".

The curl request :
curl -s -v -i -X PUT localhost:8080/machine_Amazon_EC2/r1 -H 'Content-Type: text/occi' -H 'Category: machine_Amazon_EC2; scheme="http://occiware.org/cloud#"; class="kind";'

There is the logfile from erocci : 
[erocci.txt](https://github.com/erocci/erocci_backend_dbus/files/199905/erocci.txt)

**Comment by cgourdin** [comment]
Hello Mael,
I send you an email with another cloud schema xml, test it and close this issue if it's working.
Thank you

**Comment by jeanparpaillon** [comment]
You issue has been fixed in the latest version of erocci / erocci_backend_dbus, with the following remarks:
- your OCCI schema cloud.xml is missing 

``` xml
<occi:import scheme="http://schemas.ogf.org/occi/infrastructure" />
```

wrt your schema, in your request, scheme should be: `http://occiware.org/occi/cloud#`
