### ISSUE TITLE
Owner value on all dbus method

### ISSUE THREAD

**Issue by cgourdin** [erocci/erocci_backend_dbus#4]
Hello,

The owner value doesn't appear on all method parameters, it will be valuable to have that parameter on all method call. It appears only on save methods (SaveLink and SaveResource), to make sense, we should have this value on all interfaces methods OR on none.

Thanks.

**Comment by jeanparpaillon** [comment]
"owner" metadata is not supposed to be interpreted by backend. It is saved by backend and retrieved with 'Find' method. Then, erocci core is responsible for managing authorizations through ACLs.

**Comment by cgourdin** [comment]
I use owner metadata to store and organize saved infrastructures (resources etc.), when Erocci call method Load, Erocci-Dbus-java cannot found the requested entity as owner is not set, idem for method Next, List and others. Note that i don't use it for ACLs authorization management.
My question is : Do i use this information for infrastructure fragmentation by owner ? or Only one infrastructure may be stored without owner information ?

**Comment by jeanparpaillon** [comment]
When a user request a resource, erocci first call 'Find' method. Backend must return the owner of the resource (and other metadata, see erocci-dbus.xml). If no ACL match, Load / List / Next won't be called

**Comment by cgourdin** [comment]
Ok i see, it supposed so that entityId (resource or link) is unique on all owners ?

**Comment by jeanparpaillon** [comment]
Yep, this is not an easy problem...
In the specs, entityId is supposed to be "unique in the provider's namespace".

Given that it is (more than) recommended to totally hide resources from a user to another, I suppose we should better consider the tuple {owner, entityid} to be unique.

For instance, let say user A can not see user B resources.
User A AND user B should be authorized to create 'resource1', to ensure user A can not 'see' even 'resource1'  exists for user B.

So, 2 solutions are possible:
- if (only) entityId is unique and if 'resource1' has been created by user B, user A will get a 403 when requesting 'resource1', 409 when creating 'resource1' and so on -> in this case, you don't completly hide users namespaces
- if tuple {owner, entityId} is unique in your backend, user A and user B can both create resource with the same name.

Conclusion: the API allows you to implement both behaviour, while second behaviour is preferred in general.

**Comment by cgourdin** [comment]
Thank you for your answer, i better understand the problem, to realize the second behaviour, i need to always have the tuple {owner, entityId} on method find as user A and user B can both create resource with the same name (id).  
In Erocci for instance, it's the first behaviour implementation if i understand correctly, because in find method, i have no owner in parameters and i return a tuple {owner, entityId, other metas). is that correct ?

**Comment by jeanparpaillon** [comment]
No, you can implement both behaviour in the backends, because you have both informations. 

If you look at erocci-dbus.xml, Id parameter in Find(id) is the path of the resource, but the backend must return an (opaque) id which is the internal id of the backend. If you want to implement behaviour 2, you can just return a tuple {owner, path} (or hash of). But for erocci, it is just used for calling Load(InternalId), it is not interpreted.

**Comment by cgourdin** [comment]
Ok i see, thank you for your answers, i understand now all the things, i'll make a massive update on identity management of the entities in my backend.
You can close this issue, this is not a really one thanks again.

**Comment by jeanparpaillon** [comment]
Ok, API should be better documented :/
